name: Build and Deploy to Azure using Docker

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/myapp:latest .

    - name: Push Docker Image to ACR
      run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App (Container)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/myapp:latest
