name: Run Cypress and nyc Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0' 

    - name: Install dependencies
      run: npm install

    - name: Npm debugging
      run: npm audit fix

    - name: Run backend tests
      run: npx nyc --nycrc-path .nycrc-backend mocha

    - name: Instrument frontend files
      run: npm run frontend-instrument

    - name: Run frontend tests
      run: npm run frontend-test

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage/
          .nyc_output/
