name: Run Cypress Tests and Deploy to Azure

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          cypress-${{ runner.os }}-

    - name: Install dependencies
      run: npm install

    - name: Fix permissions for binaries
      run: chmod +x ./node_modules/.bin/*

    - name: Install Cypress binary
      run: npx cypress install

    - name: Debug environment variables
      run: env

    - name: Run backend tests 
      run: npx nyc --nycrc-path .nycrc-backend mocha
      
    - name: Instrument frontend files 
      run: |
        mkdir -p instrumented
        cp -r public/* instrumented/
        npx nyc instrument public instrumented
        
    - name: Run frontend tests 
      run: |
        if [ -d ".nyc_output" ]; then rm -rf .nyc_output; fi
        npx nyc --nycrc-path .nycrc-frontend cypress run
      continue-on-error: true

    - name: Ensure screenshots folder exists
      run: mkdir -p cypress/screenshots/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-test-results
        path: cypress/screenshots/

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage/
          .nyc_output/

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_WEBAPP_NAME }}:latest .

    - name: Push Docker Image to ACR
      run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_WEBAPP_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}


    - name: Deploy to Azure Web App (Container)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_WEBAPP_NAME }}:latest
