name: Run Cypress and nyc Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install

    - name: Debug environment variables
      run: env

    - name: Ensure binaries are executable
      run: chmod +x ./node_modules/.bin/*

    - name: Instrument frontend files (Linux-specific)
      run: |
        mkdir -p instrumented
        cp -r public/* instrumented/
        npx nyc instrument public instrumented

    - name: Run frontend tests
      run: npm run frontend-test

    - name: Run backend tests
      run: npx nyc --nycrc-path .nycrc-backend mocha

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage/
          .nyc_output/
